# Wikibase with Query Service
#
# This docker-compose example can be used to build and run the images.
#
# Access Wikibase via "http://localhost:8181"
#   (or "http://$(docker-machine ip):8181" if using docker-machine)
#
# Access Query Service via "http://localhost:8282"
#   (or "http://$(docker-machine ip):8282" if using docker-machine)
version: '3'

services:
  wikibase:
    image: wikibase/wikibase:1.33-bundle
    build:
      context: ./wikibase/1.33/bundle
      dockerfile: Dockerfile
    links:
      - mysql
    ports:
     - "${MW_PORT}:80"
    volumes:
      - mediawiki-images-data:/var/www/html/images
      - quickstatements-data:/quickstatements/data
    depends_on:
    - mysql
    - elasticsearch
    networks:
      default:
        aliases:
         - ${WB_HOST}
    environment:
      - DB_SERVER=mysql.svc:3306
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - MW_ADMIN_NAME=${MW_ADMIN_NAME}
      - MW_ADMIN_PASS=${MW_ADMIN_PASS}
      - MW_ADMIN_EMAIL=${MW_ADMIN_EMAIL}
      - MW_WG_SECRET_KEY=${MW_WG_SECRET_KEY}
      - MW_ELASTIC_HOST=elasticsearch.svc
      - MW_ELASTIC_PORT=9200
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=http://localhost:${QS_PORT}
  mysql:
    image: mariadb:latest
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      default:
        aliases:
         - mysql.svc
  wdqs-frontend:
    image: wikibase/wdqs-frontend:latest
    build:
      context: ./wdqs-frontend/latest
      dockerfile: Dockerfile
    ports:
     - "${WDQS_FRONTEND_PORT}:80"
    depends_on:
    - wdqs-proxy
    networks:
      default:
        aliases:
         - wdqs-frontend.svc
    environment:
      - WIKIBASE_HOST=${WB_HOST}
      - WDQS_HOST=wdqs-proxy.svc
  wdqs:
    image: wikibase/wdqs:0.3.2
    restart: always
    build:
      context: ./wdqs/0.3.2
      dockerfile: Dockerfile
    volumes:
      - query-service-data:/wdqs/data
    command: /runBlazegraph.sh
    networks:
      default:
        aliases:
         - wdqs.svc
    environment:
      - WIKIBASE_HOST=${WB_HOST}
      - WDQS_HOST=wdqs.svc
      - WDQS_PORT=${WDQS_PORT}
    expose:
      - 9999
  wdqs-proxy:
    image: wikibase/wdqs-proxy
    build:
      context: ./wdqs-proxy/latest
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS_HOST=wdqs.svc:${WDQS_PORT}
    ports:
     - "${WDQS_BACKEND_PROXY_PORT}:80"
    depends_on:
    - wdqs
    networks:
      default:
        aliases:
         - wdqs-proxy.svc
  wdqs-updater:
    image: wikibase/wdqs:0.3.2
    build:
      context: ./wdqs/0.3.2
      dockerfile: Dockerfile
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      default:
        aliases:
         - wdqs-updater.svc
    environment:
     - WIKIBASE_HOST=${WB_HOST}
     - WDQS_HOST=wdqs.svc
     - WDQS_PORT=${WDQS_PORT}
  elasticsearch:
    image: wikibase/elasticsearch:5.6.14-extra
    build:
      context: ./elasticsearch/5.6.14-extra
      dockerfile: Dockerfile
    networks:
      default:
        aliases:
         - elasticsearch.svc
    environment:
      discovery.type: single-node
  quickstatements:
    image: wikibase/quickstatements:latest
    build:
      context: ./quickstatements/latest
      dockerfile: Dockerfile
    ports:
     - "${QS_PORT}:80"
    depends_on:
     - wikibase
    volumes:
     - quickstatements-data:/quickstatements/data
    networks:
      default:
        aliases:
         - quickstatements.svc
    environment:
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=http://localhost:${QS_PORT}
      - WB_PUBLIC_SCHEME_HOST_AND_PORT=http://localhost:${MW_PORT}
      - WIKIBASE_SCHEME_AND_HOST=${WB_HOST}
      - WB_PROPERTY_NAMESPACE=122
      - "WB_PROPERTY_PREFIX=Property:"
      - WB_ITEM_NAMESPACE=120
      - "WB_ITEM_PREFIX=Item:"

volumes:
  mediawiki-mysql-data:
  mediawiki-images-data:
  query-service-data:
  quickstatements-data:
